receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  filter/healthcheck:
    traces:
        span:
          - 'attributes["http.target"] == "/healthcheck"'
  attributes/defaults:
    actions:
      - key: environment
        value: development
        action: insert
    

exporters:
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
        insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: 
        - batch
        - filter/healthcheck
        - attributes/defaults
      exporters: [otlp/aspire]
    metrics:
      receivers: [otlp]
      processors: 
        - batch
        - attributes/defaults
      exporters: [otlp/aspire, prometheus]
    logs:
      receivers: [otlp]
      processors: 
        - batch
        - attributes/defaults
      exporters: [otlp/aspire]
