{
 "title": "RED dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_namespace_name",
    "query": {
     "query": "label_values(k8s_namespace_name)"
    }
   },
   {
    "name": "k8s_statefulset_name",
    "query": {
     "query": "label_values({\"k8s_namespace_name\"=~\"$k8s_namespace_name\"}, k8s_statefulset_name)"
    }
   },
   {
    "name": "k8s_pod_name",
    "query": {
     "query": "label_values({\"k8s_namespace_name\"=~\"$k8s_namespace_name\",\"k8s_statefulset_name\"=~\"$k8s_statefulset_name\"}, k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$k8s_namespace_name/$k8s_statefulset_name/$k8s_pod_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "HTTP LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "OK (p50)"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",error_type=~\".+\"}[$__rate_interval])) by (le))",
     "legendFormat": "Errors (p25)"
    }
   ]
  },
  {
   "title": "HTTP TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",http_response_status_code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "Error Requests/s"
    }
   ]
  },
  {
   "title": "HTTP ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",error_type=~\".+\"}[$__rate_interval])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "MESSAGING LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(messaging_masstransit_consume_duration_milliseconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "OK (p50)"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(messaging_masstransit_consume_duration_milliseconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Errors (p25)"
    }
   ]
  },
  {
   "title": "MESSAGING TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    },
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Error Requests/s"
    }
   ]
  },
  {
   "title": "MESSAGING ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval])) by (messaging_masstransit_exception_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 }, "options": { "content": "# Rows Repeated by Instances\n" } },
  { "title": "Instance: $k8s_pod_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "k8s_pod_name" },
  {
   "title": "HTTP LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "OK (p50)"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",error_type=~\".+\"}[$__rate_interval])) by (le))",
     "legendFormat": "Errors (p25)"
    }
   ]
  },
  {
   "title": "HTTP TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",http_response_status_code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "Error Requests/s"
    }
   ]
  },
  {
   "title": "HTTP ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",error_type=~\".+\"}[$__rate_interval])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "MESSAGING LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(messaging_masstransit_consume_duration_milliseconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "OK (p50)"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(messaging_masstransit_consume_duration_milliseconds_bucket{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Errors (p25)"
    }
   ]
  },
  {
   "title": "MESSAGING TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    },
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Error Requests/s"
    }
   ]
  },
  {
   "title": "MESSAGING ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_duration_milliseconds_count{k8s_namespace_name=~\"$k8s_namespace_name\",k8s_statefulset_name=~\"$k8s_statefulset_name\",k8s_pod_name=~\"$k8s_pod_name\",messaging_masstransit_exception_type=~\".+\"}[$__rate_interval])) by (messaging_masstransit_exception_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}